name: Go CI with Docker Hub and OpenShift Deployment

env:
  DOCKER_USERNAME: tbz2016 # Your Docker Hub username
  DOCKER_IMAGE_NAME: kawa-grading-service # The repository name on Docker Hub
  APP_NAME: kawagradingservice # The application name in OpenShift
  IMAGE_TAG: ${{ github.sha }} # Unique tag per commit

on:
  push:
    branches:
    - master

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.4'

    - name: Build
      run: go build ./...

    - name: Test
      run: go test ./...

  build-and-push:
    needs: build-and-test
    name: Build and Push Docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$IMAGE_TAG .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PAT }}

    - name: Push the Docker image to Docker Hub
      run: docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$IMAGE_TAG

    - name: Log in to OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true

    - name: Make script executable
      run: chmod +x .github/script.sh

    - name: Deploy to OpenShift using script # Update the deployment in OpenShift with the new Docker image
      run: .github/script.sh ${{ env.APP_NAME }} docker.io/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Check Rollout Status # Check the status of the deployment rollout to ensure it's successful
      run: oc rollout status deployment/$APP_NAME
